name: Sync Overleaf Resume
on:
  push:
    branches: [ main, master ] # runs on commits to main/master
    paths: [ '**.tex' ] # optional: only run if .tex files changed
  workflow_dispatch: # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install TeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk
        
      - name: Build PDF
        run: |
          latexmk -pdf -quiet resume.tex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
          
      # Optional: If you want to commit the PDF back to the repo
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.pdf
          git diff --staged --quiet || git commit -m "Update resume PDF"
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}